name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: default deploy
        uses: praveensounder/praveensounder@master
        with:
          aws_access_key_id: AKIA5G3MBGQF7GNPSVOO
          aws_secret_access_key: 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
          aws_region: us-east-1
          function_name: sheet
         
